---
title: "Day 4 Computational Session 1: R LESLIE MATRIX EXAMPLE"
author: "Scout Leonard"
date: "8/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating Matrices in R 

Use the `matrix()` function to wrap a series of values (a vector) into a matrix.

- Use `nrow = ` to specify number of rows 
- Use `ncol = ` to specify number of columns 
- Use `byrow = TRUE` to populate the matrix by ROWS instead of columns. 

```{r}
cats <- c(1,3,6,5,2,4,10,3,9,1.6)

# Wrap cats into a matrix 
cat_matrix <- matrix(data = cats, nrow = 4, ncol = 5, byrow = TRUE)

```


```{r}
dogs <- matrix(data = c(1,0,2,3), nrow = 2, ncol = 2, byrow = TRUE)

```

```{r}
birds <- matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow = TRUE)
```

```{r}
# Multiplying matrices
4 * dogs

# Matrix Multiplication, uses the dot product 
birds %*% dogs

```

## Leslie Matrix 

```{r}
# Write the Leslie Matrix! 
insect_leslie <- matrix(c(0,0,600,0.2,0,0,0,0.08,0.6), nrow = 3, ncol = 3, byrow = TRUE)

# Specify the initial conditions.
# What is the population in each life stage at year zero? 

insect_y0 <- c(12000, 700, 500)

#Project the population in each lifestage for year 1. 
insect_y1 <- insect_leslie %*% insect_y0
insect_y1

# Project the popualtion at each life stage for years 2, 3, and 4. 

#Year 2
insect_y2 <- insect_leslie %*% insect_y1
insect_y2

#Year 3
insect_y3 <- insect_leslie %*% insect_y2
insect_y3

#Year 4
insect_y4 <- insect_leslie %*% insect_y3
insect_y4
```

